#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

#define APP_TIMER_ENABLED 1
#define APP_TIMER_CONFIG_RTC_FREQUENCY 0
#define APP_TIMER_CONFIG_IRQ_PRIORITY 6
#define APP_TIMER_CONFIG_OP_QUEUE_SIZE 10
#define APP_TIMER_CONFIG_USE_SCHEDULER 0
#define APP_TIMER_KEEPS_RTC_ACTIVE 0
#define APP_TIMER_SAFE_WINDOW_MS 300000

#define NRF_PWR_MGMT_ENABLED 1
#define NRF_PWR_MGMT_CONFIG_DEBUG_PIN_ENABLED 0
#define NRF_PWR_MGMT_CONFIG_CPU_USAGE_MONITOR_ENABLED 0
#define NRF_PWR_MGMT_CONFIG_STANDBY_TIMEOUT_ENABLED 0

#define NRF_SDH_ENABLED 1
#define NRF_SDH_CLOCK_LF_SRC 0
#define NRF_SDH_CLOCK_LF_RC_CTIV 16
#define NRF_SDH_CLOCK_LF_RC_TEMP_CTIV 2
#define NRF_SDH_CLOCK_LF_ACCURACY 1
#define NRF_SDH_DISPATCH_MODEL 0
#define NRF_SDH_BLE_ENABLED 1
#define NRF_SDH_BLE_PERIPHERAL_LINK_COUNT 0
#define NRF_SDH_BLE_CENTRAL_LINK_COUNT 0
#define NRF_SDH_BLE_TOTAL_LINK_COUNT 0
#define NRF_SDH_BLE_GAP_DATA_LENGTH 27
#define NRF_SDH_BLE_GATT_MAX_MTU_SIZE 23
#define NRF_SDH_BLE_VS_UUID_COUNT 0
#define NRF_SDH_BLE_SERVICE_CHANGED 0

#define BLE_ADVDATA_ENABLED 1
#define NRF_BLE_GATT_ENABLED 1

#define NRF_LOG_ENABLED 0
#define NRF_LOG_BACKEND_RTT_ENABLED 0
#define NRF_LOG_BACKEND_UART_ENABLED 0
#define UART_ENABLED 0
#define NRFX_UARTE_ENABLED 0
#define NRFX_UART_ENABLED 0
#define NRF_FPRINTF_ENABLED 0
#define NRF_STRERROR_ENABLED 0

#define CLOCK_ENABLED 1
#define POWER_ENABLED 1
#define NRFX_CLOCK_ENABLED 1
#define NRFX_POWER_ENABLED 1
#define NRFX_RTC_ENABLED 1
#define NRFX_RTC1_ENABLED 1
#define NRFX_SAADC_ENABLED 0
#define NRFX_TIMER_ENABLED 0
#define NRFX_TWIM_ENABLED 0
#define NRFX_SPIM_ENABLED 0
#define NRFX_GPIOTE_ENABLED 0

#define NRF_BALLOC_ENABLED 1
#define NRF_MEMOBJ_ENABLED 1
#define NRF_SECTION_ITER_ENABLED 1
#define NRF_SORTLIST_ENABLED 1
#define NRF_ATFIFO_ENABLED 1
#define APP_ERROR_CHECK_ENABLED 1
#define HARDFAULT_HANDLER_ENABLED 1

#endif /* SDK_CONFIG_H */
